author: ScRiiPteD
database: true
description: Manages all custom plugins for XDM
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: me.scriipted.plugins.diamondmanager.DiamondManager
name: Diamond Manager
startup: postworld
url: http://xboxdm.com/
version: '1.0'
