author: tjs238
description: Manages all custom plugins for Diamond Craft
main: me.scriipted.plugins.diamondmanager.DiamondManager
name: Diamond Manager
startup: postworld
version: '2.0'
commands:
  dc:
    description: The prefix command for all the Diamond craft commands
    usage: /dc <command>
  sendi:
    description: Sends items to another player
    usage: /sendi <player name> <item> <number to send>
    aliases: si
  shout:
    description: Allows you to globaly message the server
    usage: /shout <message>
    aliases: s
  global:
    description: Chat globaly
    usage: /global <message>
    aliases: g
  mod:
    description: Sends out a Mod Helper Message
    usage: /mod
  hi:
    description: Welcome to the server
    usage: /hi
permissions:
  dc.*:
    description: Gives access to all dc permssions
    children:
      dc.pvp: true
      dc.reload: true
      dc.fly: true
      dc.StaffJoin: true
  dc.pvp:
    description: Allows you to add or remove PVP status from a region
    default: op
  dc.reload:
    description: Allows you to reload the configuration file
    default: op
  dc.fly:
    description: Allows you to fly
    default: op
  dc.StaffJoin:
    description: Allows you to join with a bang
    default: op
  dc.shout:
    description: Allows use to the /shout command
    default: op
  dc.shout.bypass:
    description: Allows you to bypass the shout timer
  dc.chat.global:
    description: Allows you to talk in global chat
    default: op
